### ISSUE TITLE
Rebuild against new Fabulous

### ISSUE THREAD

**Issue by sandeepc24** [Zaid-Ajaj/fabulous-simple-elements#3]
Could you please rebuild and release a new nuget built with latest Fabulous as I am having issues building my mobile app in release mode.

**Comment by Zaid-Ajaj** [comment]
Hello @sandeepc24, 

I can update update against latest Fabulous but AFAIK there aren't any breaking changes since 0.22.0. Can you please provide more information on what is going wrong? 

> In general it is a good practice to make libraries compatible with lowest possible version so that users of old versions of Fabulous only need to update dependencies (this library) and not Fabulous itself.

**Comment by sandeepc24** [comment]
I get following error when I build using release config

```
Severity    Code    Description    Project    File    Line    Suppression State
Error        MSB4018: The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'Fabulous.DynamicViews.ViewElement Slider::slider(Microsoft.FSharp.Collections.FSharpList`1<Slider/ISliderProp>)' in assembly: 'Fabulous.SimpleElements.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Fabulous.DynamicViews.AttributeKey`1<System.Double> Fabulous.DynamicViews.View::get__MinimumAttribKey()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by sandeepc24** [comment]
also look at https://github.com/fsprojects/Fabulous/issues/331

**Comment by Zaid-Ajaj** [comment]
Indeed there was a breaking change introduced with the slider min/max attributes. I updated Fabulous dependency, fixed and published a new version to nuget. the API from simple-elements is still the same, just update the package when it becomes available from nuget :smile:

**Comment by sandeepc24** [comment]
Thanks.
